#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/dodge

PRODUCT_COPY_FILES += \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Cinema_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Cinema_100nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Cinema_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Cinema_2nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Cinema_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Cinema_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_EP3_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_EP3_100nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_EP3_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_EP3_2nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_EP3_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_EP3_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_EsRGB_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_EsRGB_100nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_EsRGB_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_EsRGB_2nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_EsRGB_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_EsRGB_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_HS:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_HS \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_LsRGB_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_LsRGB_100nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_LsRGB_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_LsRGB_2nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_LsRGB_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_LsRGB_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Nature_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Nature_100nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Nature_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Nature_2nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Nature_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Nature_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Vivid_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Vivid_100nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Vivid_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Vivid_2nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Vivid_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA545_P_3_A0005_dsc_cmd_mode_panel_Vivid_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Cinema_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Cinema_100nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Cinema_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Cinema_2nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Cinema_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Cinema_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_EP3_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_EP3_100nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_EP3_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_EP3_2nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_EP3_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_EP3_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_EsRGB_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_EsRGB_100nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_EsRGB_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_EsRGB_2nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_EsRGB_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_EsRGB_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_HS:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_HS \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_LsRGB_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_LsRGB_100nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_LsRGB_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_LsRGB_2nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_LsRGB_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_LsRGB_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Nature_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Nature_100nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Nature_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Nature_2nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Nature_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Nature_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Vivid_100nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Vivid_100nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Vivid_2nits_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Vivid_2nits_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Vivid_pGC.txt:$(TARGET_COPY_OUT_ODM)/etc/PanelChaplin/AA569_P_3_A0019_dsc_cmd_mode_panel_Vivid_pGC.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/acdbdata/up_ve_enpuv5_ha.eai:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/up_ve_enpuv5_ha.eai \
    vendor/oneplus/dodge/proprietary/odm/etc/acdbdata/up_ve_enpuv5_hh.eai:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/up_ve_enpuv5_hh.eai \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/CameraHWConfiguration.config:$(TARGET_COPY_OUT_ODM)/etc/camera/CameraHWConfiguration.config \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/camera_engmode.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/camera_engmode.xml \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/camera_third_party_feature_config.protobuf:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_third_party_feature_config.protobuf \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/camera_unit_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_unit_config \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/camera_unit_feature_config.protobuf:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_unit_feature_config.protobuf \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/dodgefront:$(TARGET_COPY_OUT_ODM)/etc/camera/config/dodgefront \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/dodgemain:$(TARGET_COPY_OUT_ODM)/etc/camera/config/dodgemain \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/dodgetele:$(TARGET_COPY_OUT_ODM)/etc/camera/config/dodgetele \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/dodgetele2:$(TARGET_COPY_OUT_ODM)/etc/camera/config/dodgetele2 \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/dodgeultrawide:$(TARGET_COPY_OUT_ODM)/etc/camera/config/dodgeultrawide \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/oplus_camera_algo_switch_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_algo_switch_config \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/oplus_camera_algo_traversal_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_algo_traversal_config.json \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/oplus_camera_aps_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_aps_config \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/oplus_camera_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_config \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/oplus_camera_preview_decision_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_preview_decision_config.json \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/oplus_preview_decision_params.json:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_preview_decision_params.json \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/quick_visibility_white_list:$(TARGET_COPY_OUT_ODM)/etc/camera/config/quick_visibility_white_list \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/config/video_beauty_default_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/video_beauty_default_config \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/settings_fdc.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/settings_fdc.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/camera/settings_fdc_lite.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/settings_fdc_lite.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/display/qdcm_calib_data_AA545_P_3_A0005_dsc_cmd_mode_panel.json:$(TARGET_COPY_OUT_ODM)/etc/display/qdcm_calib_data_AA545_P_3_A0005_dsc_cmd_mode_panel.json \
    vendor/oneplus/dodge/proprietary/odm/etc/display/qdcm_calib_data_AA569_P_3_A0019_dsc_cmd_mode_panel.json:$(TARGET_COPY_OUT_ODM)/etc/display/qdcm_calib_data_AA569_P_3_A0019_dsc_cmd_mode_panel.json \
    vendor/oneplus/dodge/proprietary/odm/etc/mixer_paths.xml:$(TARGET_COPY_OUT_ODM)/etc/mixer_paths.xml \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_audrec_config.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_audrec_config.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_camback_calibration.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_camback_calibration.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_camfront_calibration.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_camfront_calibration.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID10_HE_App1.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID10_HE_App1.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID10_HE_App1.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID10_HE_App1.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID11_HE_Unprocess.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID11_HE_Unprocess.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID11_HE_Unprocess.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID11_HE_Unprocess.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID12_HE_VR.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID12_HE_VR.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID12_HE_VR.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID12_HE_VR.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID13_HE_USB.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID13_HE_USB.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID13_HE_USB.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID13_HE_USB.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID14_HE_USBApp1.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID14_HE_USBApp1.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID14_HE_USBApp1.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID14_HE_USBApp1.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID15_HE_BT.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID15_HE_BT.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID15_HE_BT.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID15_HE_BT.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID16_HE_BTApp1.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID16_HE_BTApp1.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID16_HE_BTApp1.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID16_HE_BTApp1.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID17_Concert.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID17_Concert.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID17_Concert.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID17_Concert.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID1_MIC_normal.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID1_MIC_normal.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID1_MIC_normal.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID1_MIC_normal.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID2_MIC_App1.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID2_MIC_App1.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID2_MIC_App1.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID2_MIC_App1.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID3_CamFront.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID3_CamFront.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID3_CamFront.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID3_CamFront.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID4_CamBack.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID4_CamBack.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID4_CamBack.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID4_CamBack.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID5_MIC_Conference.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID5_MIC_Conference.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID5_MIC_Conference.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID5_MIC_Conference.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID6_VR.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID6_VR.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID6_VR.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID6_VR.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID7_Interview.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID7_Interview.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID7_Interview.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID7_Interview.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID8_Unprocess.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID8_Unprocess.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID8_Unprocess.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID8_Unprocess.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID99_Bypass.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID99_Bypass.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID99_Bypass.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID99_Bypass.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID9_HE.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID9_HE.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID9_HE.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID9_HE.txt \
    vendor/oneplus/dodge/proprietary/odm/etc/resourcemanager.xml:$(TARGET_COPY_OUT_ODM)/etc/resourcemanager.xml \
    vendor/oneplus/dodge/proprietary/odm/etc/sdm_display_resolution_extn.xml:$(TARGET_COPY_OUT_ODM)/etc/sdm_display_resolution_extn.xml \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/config/dodge_qrd_ois_system.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/dodge_qrd_ois_system.json \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/config/json_list:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/json_list \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/config/lux_aod.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lux_aod.json \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/config/pakala_mtp_ak09919.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/pakala_mtp_ak09919.json \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/config/pakala_mtp_alsps.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/pakala_mtp_alsps.json \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/config/pakala_mtp_alsps_hw_tcs3720.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/pakala_mtp_alsps_hw_tcs3720.json \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/config/pakala_mtp_bmi26x.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/pakala_mtp_bmi26x.json \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/config/pakala_mtp_cct_rear.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/pakala_mtp_cct_rear.json \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/config/pakala_mtp_freefall.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/pakala_mtp_freefall.json \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/config/pakala_mtp_oplus_lay.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/pakala_mtp_oplus_lay.json \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/config/pakala_mtp_oplus_measurement.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/pakala_mtp_oplus_measurement.json \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/config/pakala_mtp_oplus_shaking.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/pakala_mtp_oplus_shaking.json \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/config/pakala_mtp_oplus_smart_prox.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/pakala_mtp_oplus_smart_prox.json \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/config/pakala_mtp_pocket.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/pakala_mtp_pocket.json \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/sns_gyro_cal.json \
    vendor/oneplus/dodge/proprietary/odm/etc/sensor/sensor_config.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/sensor_config.json \
    vendor/oneplus/dodge/proprietary/odm/etc/usecaseKvManager.xml:$(TARGET_COPY_OUT_ODM)/etc/usecaseKvManager.xml \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_0.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_0.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_1.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_1.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_10.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_10.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_100.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_100.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_101.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_101.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_102.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_102.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_103.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_103.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_104.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_104.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_105.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_105.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_106.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_106.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_107.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_107.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_108.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_108.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_109.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_109.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_11.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_11.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_110.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_110.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_111.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_111.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_112.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_112.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_118.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_118.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_12.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_12.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_122.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_122.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_170.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_170.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_2.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_2.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_3.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_3.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_302.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_302.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_303.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_303.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_304.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_304.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_305.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_305.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_308.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_308.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_309.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_309.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_310.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_310.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_315.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_315.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_316.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_316.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_318.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_318.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_363.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_363.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_364.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_364.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_365.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_365.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_366.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_366.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_367.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_367.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_368.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_368.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_369.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_369.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_370.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_370.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_4.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_4.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_41.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_41.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_42.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_42.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_43.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_43.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_44.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_44.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_45.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_45.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_46.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_46.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_47.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_47.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_5.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_5.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_51.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_51.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_52.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_52.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_53.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_53.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_54.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_54.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_55.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_55.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_56.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_56.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_59.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_59.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_6.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_6.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_60.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_60.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_61.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_61.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_62.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_62.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_63.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_63.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_64.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_64.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_65.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_65.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_66.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_66.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_67.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_67.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_68.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_68.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_69.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_69.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_7.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_7.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_8.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_8.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/def/effect_9.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/def/effect_9.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_0.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_0.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_1.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_1.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_105.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_105.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_106.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_106.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_107.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_107.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_109.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_109.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_2.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_2.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_3.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_3.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_309.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_309.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_310.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_310.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_315.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_315.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_316.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_316.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_318.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_318.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_363.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_363.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_364.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_364.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_4.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_4.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_46.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_46.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_47.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_47.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_54.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_54.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_6.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_6.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_7.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_7.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/9999/soft/effect_8.bin:$(TARGET_COPY_OUT_ODM)/etc/vibrator/9999/soft/effect_8.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/vibrator/vibrator_effect.json:$(TARGET_COPY_OUT_ODM)/etc/vibrator/vibrator_effect.json \
    vendor/oneplus/dodge/proprietary/odm/etc/wifi/peach/bdwlan.b0a:$(TARGET_COPY_OUT_ODM)/etc/wifi/peach/bdwlan.b0a \
    vendor/oneplus/dodge/proprietary/odm/etc/wifi/peach/bdwlan.b0c:$(TARGET_COPY_OUT_ODM)/etc/wifi/peach/bdwlan.b0c \
    vendor/oneplus/dodge/proprietary/odm/etc/wifi/peach/bdwlan.b0e:$(TARGET_COPY_OUT_ODM)/etc/wifi/peach/bdwlan.b0e \
    vendor/oneplus/dodge/proprietary/odm/etc/wifi/peach/bdwlan.b0i:$(TARGET_COPY_OUT_ODM)/etc/wifi/peach/bdwlan.b0i \
    vendor/oneplus/dodge/proprietary/odm/etc/wifi/peach/bdwlan.elf:$(TARGET_COPY_OUT_ODM)/etc/wifi/peach/bdwlan.elf \
    vendor/oneplus/dodge/proprietary/odm/etc/wifi/peach/bdwlang.b0a:$(TARGET_COPY_OUT_ODM)/etc/wifi/peach/bdwlang.b0a \
    vendor/oneplus/dodge/proprietary/odm/etc/wifi/peach/bdwlang.b0c:$(TARGET_COPY_OUT_ODM)/etc/wifi/peach/bdwlang.b0c \
    vendor/oneplus/dodge/proprietary/odm/etc/wifi/peach/bdwlang.b0e:$(TARGET_COPY_OUT_ODM)/etc/wifi/peach/bdwlang.b0e \
    vendor/oneplus/dodge/proprietary/odm/etc/wifi/peach/bdwlang.b0i:$(TARGET_COPY_OUT_ODM)/etc/wifi/peach/bdwlang.b0i \
    vendor/oneplus/dodge/proprietary/odm/etc/wifi/peach/bdwlang.elf:$(TARGET_COPY_OUT_ODM)/etc/wifi/peach/bdwlang.elf \
    vendor/oneplus/dodge/proprietary/odm/etc/wifi/peach/regdb.bin:$(TARGET_COPY_OUT_ODM)/etc/wifi/peach/regdb.bin \
    vendor/oneplus/dodge/proprietary/odm/etc/wifi/peach/regdb_version:$(TARGET_COPY_OUT_ODM)/etc/wifi/peach/regdb_version \
    vendor/oneplus/dodge/proprietary/odm/firmware/aw882xx_acf.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw882xx_acf.bin \
    vendor/oneplus/dodge/proprietary/odm/firmware/fastchg/23821/charging_hyper_mode_config.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/23821/charging_hyper_mode_config.txt \
    vendor/oneplus/dodge/proprietary/odm/firmware/fastchg/23821/single_charging_hyper_mode_config.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/23821/single_charging_hyper_mode_config.txt \
    vendor/oneplus/dodge/proprietary/odm/firmware/fastchg/23893/charging_hyper_mode_config.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/23893/charging_hyper_mode_config.txt \
    vendor/oneplus/dodge/proprietary/odm/firmware/fastchg/23893/single_charging_hyper_mode_config.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/23893/single_charging_hyper_mode_config.txt \
    vendor/oneplus/dodge/proprietary/odm/firmware/fastchg/batt_dchg_ctrl_config_table.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/batt_dchg_ctrl_config_table.txt \
    vendor/oneplus/dodge/proprietary/odm/firmware/fastchg/batt_eis_config.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/batt_eis_config.txt \
    vendor/oneplus/dodge/proprietary/odm/firmware/fastchg/batt_si_loss_config_table.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/batt_si_loss_config_table.txt \
    vendor/oneplus/dodge/proprietary/odm/firmware/fastchg/bms_heating_config.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/bms_heating_config.txt \
    vendor/oneplus/dodge/proprietary/odm/firmware/fastchg/charge_time_config.csv:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/charge_time_config.csv \
    vendor/oneplus/dodge/proprietary/odm/firmware/fastchg/charging_thermal_config_default.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/charging_thermal_config_default.txt \
    vendor/oneplus/dodge/proprietary/odm/firmware/fastchg/silicon_p_770_batt_dchg_ctrl_config_table.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/silicon_p_770_batt_dchg_ctrl_config_table.txt \
    vendor/oneplus/dodge/proprietary/odm/firmware/fastchg/silicon_p_770_batt_eis_config.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/silicon_p_770_batt_eis_config.txt \
    vendor/oneplus/dodge/proprietary/odm/firmware/fastchg/silicon_p_770_batt_si_loss_config_table.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/silicon_p_770_batt_si_loss_config_table.txt \
    vendor/oneplus/dodge/proprietary/odm/firmware/fastchg/silicon_p_770_smart_chg_config_table.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/silicon_p_770_smart_chg_config_table.txt \
    vendor/oneplus/dodge/proprietary/odm/firmware/fastchg/smart_chg_config_table.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/smart_chg_config_table.txt \
    vendor/oneplus/dodge/proprietary/odm/firmware/tof8801_firmware.bin:$(TARGET_COPY_OUT_ODM)/firmware/tof8801_firmware.bin \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/FW_S3910_BOE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/FW_S3910_BOE.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/FW_S3910_BOEB8_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/FW_S3910_BOEB8_HBP.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/FW_S3910_BOEB8_HBP_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/FW_S3910_BOEB8_HBP_FAE.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/FW_S3910_BOE_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/FW_S3910_BOE_FAE.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/FW_S3910_BOE_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/FW_S3910_BOE_HBP.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/FW_S3910_BOE_HBP_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/FW_S3910_BOE_HBP_FAE.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/FW_S3910_SAMSUNG.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/FW_S3910_SAMSUNG.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/FW_S3910_SAMSUNG_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/FW_S3910_SAMSUNG_FAE.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/FW_S3910_TIANMA.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/FW_S3910_TIANMA.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/FW_S3910_TIANMA_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/FW_S3910_TIANMA_FAE.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/FW_S3910_TIANMA_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/FW_S3910_TIANMA_HBP.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/FW_S3910_TIANMA_HBP_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/FW_S3910_TIANMA_HBP_FAE.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/GloveDetect.tflite:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/GloveDetect.tflite \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/LIB_S3910_BOEB8_HBP_TS_ALGO.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/LIB_S3910_BOEB8_HBP_TS_ALGO.so \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/LIB_S3910_BOEB8_HBP_TS_ALGO_HWASAN.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/LIB_S3910_BOEB8_HBP_TS_ALGO_HWASAN.so \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/LIB_S3910_BOEB8_HBP_TS_HAL.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/LIB_S3910_BOEB8_HBP_TS_HAL.so \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/LIB_S3910_BOE_HBP_TS_ALGO.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/LIB_S3910_BOE_HBP_TS_ALGO.so \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/LIB_S3910_BOE_HBP_TS_ALGO_HWASAN.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/LIB_S3910_BOE_HBP_TS_ALGO_HWASAN.so \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/LIB_S3910_BOE_HBP_TS_HAL.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/LIB_S3910_BOE_HBP_TS_HAL.so \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/LIMIT_S3910_BOE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/LIMIT_S3910_BOE.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/LIMIT_S3910_BOEB8_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/LIMIT_S3910_BOEB8_HBP.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/LIMIT_S3910_BOEB8_HBP_AGING.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/LIMIT_S3910_BOEB8_HBP_AGING.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/LIMIT_S3910_BOE_AGING.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/LIMIT_S3910_BOE_AGING.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/LIMIT_S3910_BOE_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/LIMIT_S3910_BOE_HBP.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/LIMIT_S3910_BOE_HBP_AGING.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/LIMIT_S3910_BOE_HBP_AGING.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/LIMIT_S3910_SAMSUNG.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/LIMIT_S3910_SAMSUNG.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/LIMIT_S3910_TIANMA.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/LIMIT_S3910_TIANMA.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/LIMIT_S3910_TIANMA_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/LIMIT_S3910_TIANMA_HBP.img \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/libIfp.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/libIfp.so \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/libaifilm.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/libaifilm.so \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/model.tflite:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/model.tflite \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/sys_edge_touch_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/sys_edge_touch_config.xml \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/sys_touch_algo_feature_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/sys_touch_algo_feature_config.xml \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/sys_touch_function_feature_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/sys_touch_function_feature_config.xml \
    vendor/oneplus/dodge/proprietary/odm/firmware/tp/23821/sys_touch_scene_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/23821/sys_touch_scene_config.xml \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_gx.b00:$(TARGET_COPY_OUT_ODM)/firmware/uff_gx.b00 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_gx.b01:$(TARGET_COPY_OUT_ODM)/firmware/uff_gx.b01 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_gx.b02:$(TARGET_COPY_OUT_ODM)/firmware/uff_gx.b02 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_gx.b03:$(TARGET_COPY_OUT_ODM)/firmware/uff_gx.b03 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_gx.b04:$(TARGET_COPY_OUT_ODM)/firmware/uff_gx.b04 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_gx.b05:$(TARGET_COPY_OUT_ODM)/firmware/uff_gx.b05 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_gx.b06:$(TARGET_COPY_OUT_ODM)/firmware/uff_gx.b06 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_gx.b07:$(TARGET_COPY_OUT_ODM)/firmware/uff_gx.b07 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_gx.b08:$(TARGET_COPY_OUT_ODM)/firmware/uff_gx.b08 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_gx.mdt:$(TARGET_COPY_OUT_ODM)/firmware/uff_gx.mdt \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_spi.b00:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b00 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_spi.b01:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b01 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_spi.b02:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b02 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_spi.b03:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b03 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_spi.b04:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b04 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_spi.b05:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b05 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_spi.b06:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b06 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_spi.b07:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b07 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_spi.b08:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.b08 \
    vendor/oneplus/dodge/proprietary/odm/firmware/uff_spi.mdt:$(TARGET_COPY_OUT_ODM)/firmware/uff_spi.mdt \
    vendor/oneplus/dodge/proprietary/vendor/etc/acdbdata/sun_mtp/acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/sun_mtp/acdb_cal.acdb \
    vendor/oneplus/dodge/proprietary/vendor/etc/display/sdm_display_resolution_extn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/sdm_display_resolution_extn.xml \
    vendor/oneplus/dodge/proprietary/vendor/etc/display_apollo_list_AA569_P_3_A0019_dsc_cmd_mode_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display_apollo_list_AA569_P_3_A0019_dsc_cmd_mode_panel.xml \
    vendor/oneplus/dodge/proprietary/vendor/etc/display_dbvgain_config_AA569_P_3_A0019_dsc_cmd_mode_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display_dbvgain_config_AA569_P_3_A0019_dsc_cmd_mode_panel.xml \
    vendor/oneplus/dodge/proprietary/vendor/etc/display_dbvgain_config_v2_AA569_P_3_A0019_dsc_cmd_mode_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display_dbvgain_config_v2_AA569_P_3_A0019_dsc_cmd_mode_panel.xml \
    vendor/oneplus/dodge/proprietary/vendor/etc/display_demura_config_AA569_P_3_A0019_dsc_cmd_mode_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display_demura_config_AA569_P_3_A0019_dsc_cmd_mode_panel.xml \
    vendor/oneplus/dodge/proprietary/vendor/etc/display_demura_config_v2_AA569_P_3_A0019_dsc_cmd_mode_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display_demura_config_v2_AA569_P_3_A0019_dsc_cmd_mode_panel.xml \
    vendor/oneplus/dodge/proprietary/vendor/etc/ltm_config_AA569_P_3_A0019_dsc_cmd_mode_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ltm_config_AA569_P_3_A0019_dsc_cmd_mode_panel.xml \
    vendor/oneplus/dodge/proprietary/vendor/etc/sensors/config/json.lst:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/json.lst \
    vendor/oneplus/dodge/proprietary/vendor/etc/sensors/config/qsh_camera_common.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_common.json \
    vendor/oneplus/dodge/proprietary/vendor/etc/sensors/config/qsh_camera_dodgefront_3.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_dodgefront_3.json \
    vendor/oneplus/dodge/proprietary/vendor/etc/sensors/config/qsh_camera_imx480_3.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_imx480_3.json \
    vendor/oneplus/dodge/proprietary/vendor/etc/sensors/config/qsh_camera_imx615_3.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_imx615_3.json \
    vendor/oneplus/dodge/proprietary/vendor/etc/sensors/config/qsh_camera_imx688_6.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_imx688_6.json \
    vendor/oneplus/dodge/proprietary/vendor/etc/sensors/config/qsh_camera_imx688_6_actuator.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_imx688_6_actuator.json \
    vendor/oneplus/dodge/proprietary/vendor/etc/sensors/config/qsh_camera_ov32c4c_4.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_ov32c4c_4.json \
    vendor/oneplus/dodge/proprietary/vendor/etc/spr_cfg_AA569_P_3_A0019_dsc_cmd_mode_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/spr_cfg_AA569_P_3_A0019_dsc_cmd_mode_panel.xml

PRODUCT_PACKAGES += \
    sensors.qsh
